# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e8db6b1e9b06ce7f8d8f3811846083a8087f7906903bdf3014858f3b2bd92808efac65b08b4e8ecf1532ad87d0e25bb89a52f84ade5635637939e7b8196e3e9

test:
  secret_key_base: 4f86b675e7f9e48149d8ebdebc6e63d45aa7b77c800247612692f74fbaac08a5c569f8030515ba8f7e8545981229f4b30f241e1661d214ca7b8f8ccf721fc409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
